services:
  - type: web
    name: siraha-bazaar
    env: node
    buildCommand: |
      npm install --legacy-peer-deps
      cd client
      npm install --legacy-peer-deps
      npm run build
      cd ..
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    plan: free 