services:
  - type: web
    name: siraha-bazaar
    env: node
    buildCommand: |
      npm install
      cd client
      npm install
      npm install -g vite
      npm run build
      cd ..
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    plan: free 